### ISSUE TITLE
Lab 2 Feedback

### ISSUE THREAD

**Issue by alanarnholt** [STT3851-Fall2019/lab2-thomaskeener#1]
@thomaskeener 

1) On line 108, please use r inline coding to the the mean and standard deviation values versus hardcoding the answers.

2) It looks like you used the packages.bib file from the previous assignment....recreate the packages.bib file in the document .... hide all of this code from the reader.

The rest looks great.

**Comment by thomaskeener** [comment]
@alanarnholt 

The last commit should have fixed the issues.

**Comment by alanarnholt** [comment]
@thomaskeener looks good!
